USE reservation;

CREATE TABLE IF NOT EXISTS flight
(
    ID BIGINT  NOT NULL AUTO_INCREMENT,
    FLIGHT_NUMBER VARCHAR(20)  NOT NULL,
    OPERATING_AIRLINES VARCHAR(20)  NOT NULL,
    DEPARTURE_CITY VARCHAR(20)  NOT NULL,
    ARRIVAL_CITY VARCHAR(20)  NOT NULL,
    DATE_OF_DEPARTURE DATE  NOT NULL,
    ESTIMATED_DEPARTURE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS passenger
(
    ID         BIGINT NOT NULL AUTO_INCREMENT,
    FIRST_NAME       VARCHAR(256),
    LAST_NAME    VARCHAR(256),
    MIDDLE_NAME   VARCHAR(256),
    EMAIL VARCHAR(50),
    PHONE VARCHAR(10),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS reservation
(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CHECKED_IN TINYINT(1),
    NUMBER_OF_BAGS INT,
    PASSENGER_ID BIGINT,
    FLIGHT_ID BIGINT,
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (PASSENGER_ID) REFERENCES passenger(ID) ON DELETE CASCADE,
    FOREIGN KEY (FLIGHT_ID) REFERENCES flight(ID)
);